version: '3.0'
networks:
  hashring-network: {}
volumes: {}
services:
  server:
    build: ./server
    environment:
      - HASHRING_PORT=7373
      - DOCKER_IMAGE_NAME=consistent-hashing-websocket-server_server
      - DOCKER_HASHRING_NETWORK_NAME=consistent-hashing-websocket-server_hashring-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - hashring-network
  proxy:
    build: ./proxy
    environment:
      - HASHRING_BASE_HOST=server
      - HASHRING_BASE_PORT=7373
      - PORT=8080
    networks:
      - hashring-network
    ports:
      - 8080:8080
    depends_on:
      - server
